language: ruby

services:
  - postgresql
  - mysql
bundler_args: --without tools benchmarks
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database rom_factory;' -U postgres
after_success:
  - '[ -d coverage ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.6.1
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - jruby-9.2.5.0
env:
  global:
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
