name: ci

on:
  push:
    paths:
      - .github/workflows/custom_ci.yml
      - lib/**
      - spec/**
      - Gemfile
      - "*.gemspec"
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.8
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: rom_factory
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - 2.6
          - 2.5
          - 2.4
          - jruby
        faker:
          - faker-1
          - faker-2
        include:
          - ruby: 2.6
            faker: faker-2
            coverage: "true"
          - ruby: jruby
            database_url: jdbc:postgresql://localhost/rom_factory
    env:
      CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
      CODACY_RUN_LOCAL: true
      COVERAGE: ${{matrix.coverage}}
      DATABASE_URL: ${{matrix.database_url}}
      FAKER: ${{matrix.faker}}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends libpq-dev
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Install bundler
        run: gem install bundler
      - name: Bundle
        run: bundle install --jobs 4 --retry 3 --without tools docs benchmarks
      - name: Run all tests
        run: |
          [ -z $DATABASE_URL ] && export DATABASE_URL="postgres://localhost/rom_factory"
          bundle exec rake
