name: ci

on:
  push:
    paths:
      - .github/workflows/ci.yml
      - lib/**
      - spec/**
      - Gemfile
      - "*.gemspec"
  pull_request:
    branches:
      - master

jobs:
  tests-mri:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.8
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: rom_factory
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.6.x", "2.5.x", "2.4.x"]
        appraisal: ["faker_1", "faker_2"]
        include:
          - ruby: "2.6.x"
            coverage: "true"
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends libpq-dev
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Install bundler
        run: gem install bundler
      - name: Bundle
        env:
          BUNDLE_GEMFILE: gemfiles/${{matrix.appraisal}}.gemfile
        run: bundle install --jobs 4 --retry 3 --without tools docs benchmarks
      - name: Run all tests
        env:
          COVERAGE: ${{matrix.coverage}}
          BUNDLE_GEMFILE: gemfiles/${{matrix.appraisal}}.gemfile
        run: bundle exec rake
      - name: Download test reporter
        if: "matrix.coverage == 'true'"
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        run: |
          [ "$CC_TEST_REPORTER_ID" = "" ] && exit 0
          mkdir -p tmp/
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
          chmod +x ./tmp/cc-test-reporter
          ./tmp/cc-test-reporter before-build
      - name: Send coverage results
        if: "matrix.coverage == 'true'"
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          GIT_COMMIT_SHA: ${{github.sha}}
          GIT_BRANCH: ${{github.ref}}
          GIT_COMMITTED_AT: ${{github.event.head_commit.timestamp}}
        run: |
          [ "$CC_TEST_REPORTER_ID" = "" ] && exit 0
          GIT_BRANCH=`ruby -e "puts ENV['GITHUB_REF'].split('/', 3).last"` \
          GIT_COMMITTED_AT=`ruby -r time -e "puts Time.iso8601(ENV['GIT_COMMITTED_AT']).to_i"` \
          ./tmp/cc-test-reporter after-build

  tests-others:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:10.8
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: rom_factory
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        image: ["jruby:9.2.9", "ruby:rc"]
        include:
          - image: "jruby:9.2.9"
            database_url: "jdbc:postgresql://db/rom_factory"
          - image: "ruby:rc"
            database_url: "postgres://db/rom_factory"
    container:
      image: ${{matrix.image}}
    steps:
      - uses: actions/checkout@v1
      - name: Install git
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git
      - name: Install dependencies
        run: apt-get install -y --no-install-recommends libpq-dev
      - name: Install bundler
        run: gem install bundler
      - name: Bundle
        run: bundle install --jobs 4 --retry 3 --without tools docs benchmarks
      - name: Run all tests
        run: bundle exec rake
        env:
          DATABASE_URL: ${{matrix.database_url}}
